In [226]:
"""
This notebook is for parctice only.
The course is "Machine Learning Foundation" by H.T. Lin, NTU, on Cousera.

"""

import re
import numpy as np

def readData(filename):
    result = []
    with open(filename,'r') as f:
        str_line = f.readline()
        while str_line:
            re_line = re.split(pattern='\n| |\b|\t', string=str_line)[0:-1]
            nu_line = [float(i) for i in re_line]
            result.append(nu_line)
            str_line = f.readline() #next line
    result = np.array(result)
    return result

data = readData("\dataset\hw1_15_train.txt")

data_X = data[:,:-1]
data_Y = np.int32(data[:,-1])

size = data_X.shape[0]
dims = data_X.shape[1]
print('Data size:{}, Dimension:{}'.format(size, dims))

Data size:400, Dimension:4


In [161]:
data_X[0:10]

array([[0.97681 , 0.10723 , 0.64385 , 0.29556 ],
       [0.67194 , 0.2418  , 0.83075 , 0.42741 ],
       [0.20619 , 0.23321 , 0.81004 , 0.98691 ],
       [0.51583 , 0.055814, 0.92274 , 0.75797 ],
       [0.70893 , 0.10836 , 0.33951 , 0.77058 ],
       [0.55743 , 0.67804 , 0.061044, 0.72689 ],
       [0.15654 , 0.75584 , 0.01122 , 0.42598 ],
       [0.50462 , 0.15137 , 0.33878 , 0.41881 ],
       [0.22657 , 0.59272 , 0.24103 , 0.46221 ],
       [0.49174 , 0.65115 , 0.24622 , 0.24796 ]])

In [162]:
data_Y[0:10]

array([ 1,  1,  1,  1,  1,  1, -1,  1, -1, -1])

In [266]:
def pla(X, Y):
    """
    Use formula: w_new = w + y*x to update w if the sign of wx and y are different (wx*y is negative)
    After we updated the w when we find such different on one of the data for some cycle c, 
    we should keep finish that cycle rather than break that iteration.
    """
  
    # data shape
    size = X.shape[0]
    dims = X.shape[1]
    
    # initialization weights of zeros, and insert x0=1 to the end of x
    X0 = np.ones((size,1))
    X = np.concatenate((X, X0), axis=1) #insert ones horizontaly
    W = np.zeros((dims+1))
    
    # define loop control parameters
    iter_times = 0
    error_indices = []
    correct_times_prev = 0
    correct_times = 0
    #print(X)
        
    while True:     
        #Search for error x index such that sign(w*x) != y        
        for i in range(0, size):         
            x = X[i]
            y = Y[i]
            pred = np.dot(W, x) 
            
            
            #update the weights if the sign of pred * y is negative
            if pred * y <= 0:
                error_indices.append(i)
                correct_times = len(error_indices)
                W += y*x
                                
        #break while loop if all example is checked
        if correct_times == correct_times_prev  or iter_times > 1000:
            break
            
        #print(correct_times_prev, correct_times)
        correct_times_prev = correct_times    
        iter_times += 1
        
    return W, correct_times

In [278]:
#Answer for HW1-15
pla(X=data_X, Y=data_Y)

(array([ 3.0841436, -1.583081 ,  2.391305 ,  4.5287635, -3.       ]), 45)

In [268]:
def random_index(N, random_seed=0):
    import random
    random.seed(random_seed)
    items = list(range(0, N))
    random_items = random.sample(items, len(items))
    return random_items

In [275]:
def pla_optimized(X, Y, random_seed=0, eta=1):
    """
    This version perform a random index list and eta when updating w. 
    Note the original version is just under the condition with sorted indice of data and eta=1.
    
    ---
    Use formula: w_new = w + y*x to update w if the sign of wx and y are different (wx*y is negative)
    After we updated the w when we find such different on one of the data for some cycle c, 
    we should keep finish that cycle rather than break that iteration.
    """
  
    # data shape
    size = X.shape[0]
    dims = X.shape[1]
    
    # initialization weights of zeros, and insert x0=1 to the end of x
    X0 = np.ones((size,1))
    X = np.concatenate((X, X0), axis=1) #insert ones horizontaly
    W = np.zeros((dims+1))
    
    # define loop control parameters
    iter_times = 0
    error_indices = []
    correct_times_prev = 0
    correct_times = 0
    #print(X)
        
    while True:     
        #Search for error x index such that sign(w*x) != y        
        for i in random_index(N=size, random_seed=random_seed):         
            x = X[i]
            y = Y[i]
            pred = np.dot(W, x) 
            
            
            #update the weights if the sign of pred * y is negative
            if pred * y <= 0:
                error_indices.append(i)
                correct_times = len(error_indices)
                W += y*x
                                
        #break while loop if all example is checked
        if correct_times == correct_times_prev  or iter_times > 1000:
            break
            
        #print(correct_times_prev, correct_times)
        correct_times_prev = correct_times    
        iter_times += 1
        
    return W, correct_times

In [284]:
def avg_correct_times(experiment_times, random_seed=0, eta=1):
    correct_times = np.zeros((experiment_times))
    
    print("experiment_times:")
    
    for i in range(experiment_times):
        if random_seed % 100 == 0:
            print("{} / {}".format(random_seed, experiment_times))
        correct_times[i] = pla_optimized(X=data_X, Y=data_Y, random_seed=random_seed, eta=eta)[1]
        random_seed += 1
        
    avg_correct_times = np.mean(correct_times)
    return avg_correct_times

In [280]:
#Answer for HW1-16
avg_correct_times(experiment_times=2000, random_seed=0, eta=1)

experiment_times:
0 / 2000
100 / 2000
200 / 2000
300 / 2000
400 / 2000
500 / 2000
600 / 2000
700 / 2000
800 / 2000
900 / 2000
1000 / 2000
1100 / 2000
1200 / 2000
1300 / 2000
1400 / 2000
1500 / 2000
1600 / 2000
1700 / 2000
1800 / 2000
1900 / 2000


39.763

In [282]:
#Answer for HW1-17: learning rate eta set to be 0.5
avg_correct_times(experiment_times=2000, random_seed=0, eta=0.5)

experiment_times:
0 / 2000
100 / 2000
200 / 2000
300 / 2000
400 / 2000
500 / 2000
600 / 2000
700 / 2000
800 / 2000
900 / 2000
1000 / 2000
1100 / 2000
1200 / 2000
1300 / 2000
1400 / 2000
1500 / 2000
1600 / 2000
1700 / 2000
1800 / 2000
1900 / 2000


39.763

In [286]:
data_18_train = readData("C://Users/YCChen/Desktop/hw1_18_train.txt")
data_18_test = readData("C://Users/YCChen/Desktop/hw1_18_test.txt")

data_18_train_X = data_18_train[:,:-1]
data_18_train_Y = np.int32(data_18_train[:,-1])
data_18_test_X = data_18_test[:,:-1]
data_18_test_Y = np.int32(data_18_test[:,-1])

train_size = data_18_train_X.shape[0]
test_size = data_18_test_X.shape[0]
dims = data_18_train_X.shape[1]
print('Training Data size:{}, Testing Data size:{}, Dimension:{}'.format(train_size, test_size, dims))

Training Data size:500, Testing Data size:500, Dimension:4


In [336]:
def pocket_weight_evaluation(W, X, Y):
    evaluation_result = 0
    size = X.shape[0]
    for i in range(size):
        x = X[i]
        y = Y[i]
        pred = np.dot(W, x)
        if pred * y <= 0:
            evaluation_result += 1/size
    #print(evaluation_result)
    
    return evaluation_result

In [430]:
def pocket(X, Y, random_seed=0, max_correct_times = 50, pocket=1):
    """
    if pocket == 0 , this becomes a PLA with fixed corrected times
    """
    # data shape
    size = X.shape[0]
    dims = X.shape[1]
    
    # initialization weights of zeros, and insert x0=1 to the end of x
    X0 = np.ones((size,1))
    X = np.concatenate((X, X0), axis=1) #insert ones horizontaly
    W = np.zeros((dims+1))
    
    # define loop control parameters
    iter_times = 0
    error_indices = []
    correct_times_prev = 0 # no use in pocket
    correct_times = 0
    evaluation_flag = False
    evaluation_prev = 1.01
    evaluation = 1
    W_best = np.copy(W) #don't use W_best = W, W_best will change along with W
    #print(X)
        
    while correct_times < max_correct_times:     
        #Search for error x index such that sign(w*x) != y        
        random_range = random_index(N=size, random_seed=random_seed)
        for i in random_range:         
            x = X[i]
            y = Y[i]
            pred = np.dot(W, x) 
            
            
            #update the weight if the sign of pred * y is negative
            if pred * y <= 0:
                error_indices.append(i)
                correct_times = len(error_indices)
                W += y*x
                evaluation_flag = True
            else: evaluation_flag = False
                
            #When W is updated, and pocket=1, it will be turn on to evaluate no. of errors,
            #check the # of error with W just updated above
            if pocket == 1 and evaluation_flag:
                evaluation = pocket_weight_evaluation(W, X, Y)
                
                # compare # of error with ones in the pocket, if newest is better, we replace the old one by it.
                if evaluation < evaluation_prev:
                    evaluation_prev = evaluation
                    W_best = np.copy(W)
            
            #Directly pass W to W_best if pocket == 0, and it's just a pla 
            if pocket == 0:
                W_best = np.copy(W)
                
            #break loop rule
            if correct_times >= max_correct_times:
                break
                
                                
        #break the while loop if all example has been checked and there are no more updating on the weight. 
        #(only if the data is linearly separable)
        #
        # for pocket we don't break while, so the following line is hidden
        #
        #if correct_times == correct_times_prev or iter_times > 1000:
        #    break
        
        correct_times_prev = correct_times # no use in pocket
        iter_times += 1
        
    return W_best, correct_times

In [431]:
# Derive W_best list 2000 times with different seeds...
W_best_list = []
experiment_times = 2000

for random_seed in range(experiment_times):
    if random_seed % 100 == 0:
            print("{} / {}".format(random_seed, experiment_times))
    W_best_list.append(pocket(data_18_train_X, data_18_train_Y, random_seed=random_seed, max_correct_times = 50)[0])

0 / 2000
100 / 2000
200 / 2000
300 / 2000
400 / 2000
500 / 2000
600 / 2000
700 / 2000
800 / 2000
900 / 2000
1000 / 2000
1100 / 2000
1200 / 2000
1300 / 2000
1400 / 2000
1500 / 2000
1600 / 2000
1700 / 2000
1800 / 2000
1900 / 2000


In [432]:
error_rate = []

X0 = np.ones((test_size,1))
data_18_test_X_ = np.concatenate((data_18_test_X, X0), axis=1) #insert ones horizontaly

for W_best in W_best_list:
    error_rate.append(pocket_weight_evaluation(W=W_best, X=data_18_test_X_, Y=data_18_test_Y))

In [433]:
#Answer for HW1-18:
np.mean(error_rate)

0.13208800000000007

In [434]:
# Derive W_best list 2000 times with different seeds...
W_best_list1 = []
experiment_times = 2000

for random_seed in range(experiment_times):
    if random_seed % 100 == 0:
            print("{} / {}".format(random_seed, experiment_times))
    W_best_list1.append(pocket(data_18_train_X, data_18_train_Y, random_seed=random_seed, max_correct_times = 50, pocket=0)[0])


0 / 2000
100 / 2000
200 / 2000
300 / 2000
400 / 2000
500 / 2000
600 / 2000
700 / 2000
800 / 2000
900 / 2000
1000 / 2000
1100 / 2000
1200 / 2000
1300 / 2000
1400 / 2000
1500 / 2000
1600 / 2000
1700 / 2000
1800 / 2000
1900 / 2000


In [435]:
error_rate1 = []

for W_best1 in W_best_list1:
    error_rate1.append(pocket_weight_evaluation(W=W_best1, X=data_18_test_X_, Y=data_18_test_Y))

In [436]:
#Answer for HW1-19:
np.mean(error_rate1)

0.35972800000000016

In [437]:
# Derive W_best__ list 2000 times with different seeds...
W_best_list_100 = []
experiment_times = 2000

for random_seed in range(experiment_times):
    if random_seed % 100 == 0:
            print("{} / {}".format(random_seed, experiment_times))
    W_best_list_100.append(pocket(data_18_train_X, data_18_train_Y, random_seed=random_seed, max_correct_times = 100)[0])

0 / 2000
100 / 2000
200 / 2000
300 / 2000
400 / 2000
500 / 2000
600 / 2000
700 / 2000
800 / 2000
900 / 2000
1000 / 2000
1100 / 2000
1200 / 2000
1300 / 2000
1400 / 2000
1500 / 2000
1600 / 2000
1700 / 2000
1800 / 2000
1900 / 2000


In [438]:
error_rate100 = []

for W_best100 in W_best_list_100:
    error_rate100.append(pocket_weight_evaluation(W=W_best100, X=data_18_test_X_, Y=data_18_test_Y))

In [439]:
#Answer for HW1-20:
np.mean(error_rate100)

0.11416900000000009